Tutorials from blog
mlbench/mlbench-docs pull request #24
Opened 2020-05-22 14:08 UTC by giorgiosav

Added 2 tutorials from blog. Omitted the Google Cloud tutorial because it's outdated now that we have the CLI.
Resolves #23

2020-05-22 14:38 UTC, martinjaggi requested changes

2020-05-22 14:38 UTC, martinjaggi commented on tutorials.rst
> +At this point, the script could technically already run in MLBench. But so far it would not report back to the Dashboard and you wouldn't be able to see stats during training. So let's add some repor
but would it already produce results in the result folder? good to clearly describe input/output of a run so that users know what to expect (CLI is fine at first, and later also with dashboard. also say that there are the two possibilities to run, as the user prefers)

2020-05-22 14:38 UTC, martinjaggi commented on tutorials.rst
> +That's it. Now the training will report the loss of each worker back to the Dashboard and show it in a nice Graph.
and to the result file too?

2020-05-22 14:38 UTC, martinjaggi commented on tutorials.rst
> +
should we say sth why it's `task1`?

2020-05-22 14:38 UTC, martinjaggi commented on tutorials.rst
> +Now we're all set to start our experiment. Hit ``Add Run`` and that's it. You just ran a custom model on MLBench.
does it work in CLI as well? or do we need two parts of the tutorial middle part, to explain in dashboard and alternatively in CLI?

2020-05-22 14:38 UTC, martinjaggi commented on tutorials.rst
> +To create a new Google cloud cluster, simply run (this might take a couple of minutes):
add a comment on other clouds being supported as well (is there a place to link to in the docu?)

2020-05-22 14:38 UTC, martinjaggi commented on tutorials.rst
> +Adding an existing Pytorch model to an MLBench task
I'd suggest `Adding an existing PyTorch training script into MLbench`

2020-05-22 14:38 UTC, martinjaggi commented on tutorials.rst
> +MLBench is designed to easily be used with third-party models, allowing for quick and fair comparisons and saving all of the hassle that's needed to implement your own baselines for comparison.
good. after fair comparisons add `by standardizing the data distribution, evaluation dataset and providing evaluation code.`.

2020-05-22 15:20 UTC, giorgiosav commented on tutorials.rst
> +At this point, the script could technically already run in MLBench. But so far it would not report back to the Dashboard and you wouldn't be able to see stats during training. So let's add some repor
My guess is no, but I think @Panaetius know the reply to this better. I'll add some info about the CLI and output folder.

2020-05-25 08:54 UTC, Panaetius commented on tutorials.rst
> +At this point, the script could technically already run in MLBench. But so far it would not report back to the Dashboard and you wouldn't be able to see stats during training. So let's add some repor
No it wouldn't produce results in the official format (only whatever is being printed in the image itself)

2020-05-25 08:54 UTC, Panaetius commented on tutorials.rst
> +That's it. Now the training will report the loss of each worker back to the Dashboard and show it in a nice Graph.
Yes

2020-05-25 09:04 UTC, Panaetius requested changes
Thank you, good work!

2020-05-25 09:04 UTC, Panaetius commented on tutorials.rst
> +    $ docker build -t mlbench/pytorch-tutorial:latest mlbench-pytorch-tutorial/
```suggestion
    $ docker build -t <user|organisation>/<name>:latest mlbench-pytorch-tutorial/
```

I think we should write the commands this way. We mention above that the user should change it, but it's common to not read all the text and just copy-paste commands. This way it's clearer that something needs to be changed. Maybe also with a short sentence on how to get this.

2020-05-25 09:04 UTC, Panaetius commented on tutorials.rst
> +and will have access to the training data and results once the run is finished
You can download the intermediate results with the `mlbench download` command as well, it doesn't have to be finished, they just won't contain the official result yet.

2020-05-25 11:34 UTC, martinjaggi commented on tutorials.rst
> +At this point, the script could technically already run in MLBench. But so far it would not report back to the Dashboard and you wouldn't be able to see stats during training. So let's add some repor
(can add to the text that results go both to the gui and to the results folder. not sure how we decided if this tutorial here is gui only or can be done both in cli or gui)

2020-05-25 11:34 UTC, martinjaggi commented on tutorials.rst
> +That's it. Now the training will report the loss of each worker back to the Dashboard and show it in a nice Graph.
can you add to the text that the reported results are going into the result file as well?

2020-05-25 12:13 UTC, giorgiosav commented
I rewrote some parts to include info on the result files from the CLI and fixed a couple of errors.

2020-05-26 12:08 UTC, Panaetius approved these changes
🚀

2020-05-26 14:26 UTC, martinjaggi approved these changes

2020-05-26 15:48 UTC, merged