Add gnmt doc
mlbench/mlbench-docs pull request #26
Opened 2020-06-29 15:27 UTC by ehoelzl

Update to the project documentation:
- Remove authors as instructed
- Rename tasks and group them
- Verify and change the hyper-parameters

2020-06-30 12:56 UTC, Panaetius approved these changes

2020-06-30 12:57 UTC, martinjaggi requested changes

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +Task 0: Communication Backend
Task 0: Communication Backend Raw Performance

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +0.a PyTorch All-reduce
just all-reduce, doesn't need to be pytorch in the task (but the ref impl is pytorch)

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    For this benchmark implementation, we use 20 layer ResNet called ResNet20.
typo 'a 20 lay...' (and maybe add a reference if there is an obvious one)

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
>        + scaling and warmup: apply ``linear scaling rule`` mentioned in :cite:`goyal2017accurate`. The learning rate per worker is scaled from
learning rate per worker, should be same as global learning rate, no? try to avoid confusion. if per worker can be skipped let's remove it

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    There is only one worker per node; each worker uses 3 cpus. The bandwidth between two nodes is around 7.5Gbit/s.
upper case cpus. and scaling result should first be described for GPUs, no? CPUs can be mentioned after it

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    - regularization rate: :math:`L1=0, L2 = 0.0000025`
looks good.  regularization rate -> regularization parameters

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    There is only one worker per node; each worker uses 3 cpus. The bandwidth between two nodes is around 7.5Gbit/s.
CPUs (do a global search and replace)

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    We benchmark the `GNMT <https://arxiv.org/abs/1609.08144>`_, which follows the sequence-to-sequence learning framework,
the GNMT machine translation model

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    vanishing/exploding gradients when too many layers are used.
potentially add a reference (paper or MLperf), to be as reproducible as possible?

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    We use Distributed Adam as the optimizer. Before each weight update, gradients on all workers are average using an `all_reduce` operation.
add reference if possible

2020-06-30 12:57 UTC, martinjaggi commented on benchmark-tasks.rst
> +    While initial results reported are from google kubernetes engine, AWS will be supported very soon.
G

2020-07-01 11:02 UTC, ehoelzl commented on benchmark-tasks.rst
> +    There is only one worker per node; each worker uses 3 cpus. The bandwidth between two nodes is around 7.5Gbit/s.
Maybe remove completely this part and keep the hardware mentioned in the Results ?

2020-07-01 11:07 UTC, martinjaggi commented
sounds good

anyway it might make sense for each task to have the main things first,
followed by a small 'fine print'/technical details section?

On Wed, Jul 1, 2020, 13:02 Edoardo Holzl <notifications@github.com> wrote:

> *@ehoelzl* commented on this pull request.
> ------------------------------
>
> In benchmark-tasks.rst
> <https://github.com/mlbench/mlbench-docs/pull/26#discussion_r448286412>:
>
> > @@ -91,24 +104,26 @@ Implementation details:
>
>  #. **Environments for Scaling Task**
>      For the scaling task, we use `n1-standard-4 <https://cloud.google.com/compute/pricing>`_ type instances with 50GB disk size.
> -    There is only one worker per node; each worker uses 2.5 cpus. The bandwidth between two nodes is around 7.5Gbit/s.
> +    There is only one worker per node; each worker uses 3 cpus. The bandwidth between two nodes is around 7.5Gbit/s.
>
> Maybe remove completely this part and keep the hardware mentioned in the
> Results ?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlbench/mlbench-docs/pull/26#discussion_r448286412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDIMRZXWKGRKBWJR4UWZWTRZMJVNANCNFSM4OLKRKOQ>
> .
>

2020-07-01 11:11 UTC, ehoelzl commented on benchmark-tasks.rst
> +    vanishing/exploding gradients when too many layers are used.
Paper is referenced right above. I can add MLPerf's implementation as reference too if needed

2020-07-01 11:34 UTC, martinjaggi commented
ok. ideally we'd use the same referencing format for all papers (also the
goyal one for LR scaling which is currently at the end or in a footnote.)
whatever is easiest.

On Wed, Jul 1, 2020 at 1:12 PM Edoardo Holzl <notifications@github.com>
wrote:

> *@ehoelzl* commented on this pull request.
> ------------------------------
>
> In benchmark-tasks.rst
> <https://github.com/mlbench/mlbench-docs/pull/26#discussion_r448290985>:
>
> > +3a. TODO
> +""""""""
> +
> +Task 4: Machine Translation
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^
> +
> +.. _benchmark-task-4a:
> +4.a LSTM, WMT16 EN-DE
> +"""""""""""""""""""""
> +
> +
> +#. **Model**
> +    We benchmark the `GNMT <https://arxiv.org/abs/1609.08144>`_, which follows the sequence-to-sequence learning framework,
> +    and uses stacked residual LSTM connections in the encoder and decoder modules. The residual connections allow
> +    for deeper stacked LSTM layers, as without residuals, the stack typically suffer from
> +    vanishing/exploding gradients when too many layers are used.
>
> Paper is referenced right above. I can add MLPerf's implementation as
> reference too if needed
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlbench/mlbench-docs/pull/26#discussion_r448290985>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDIMR3FKL5MKJJMO54EEZDRZMKYJANCNFSM4OLKRKOQ>
> .
>

2020-07-01 12:12 UTC, martinjaggi commented
in the results stucture, can you fuse Machine Type + GPU Type into one item, maybe called `System Hardware` or similar?

2020-07-01 12:12 UTC, martinjaggi approved these changes

2020-08-03 18:44 UTC, martinjaggi commented
can we merge this? maybe has to be rebased to latest version?

2020-09-08 11:21 UTC, merged